# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxDataSourceReactorKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxDataSourceReactorKit
    pod 'SnapKit', '~> 5.0.0'
    pod 'Then'
    pod 'RxSwift', '~> 5'
    pod 'RxCocoa', '~> 5'
pod 'ReusableKit'
pod 'ReusableKit/RxSwift'  # with RxSwift extension
pod 'ReactorKit'
pod 'RxDataSources'
  target 'RxDataSourceReactorKitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxDataSourceReactorKitUITests' do
    # Pods for testing
  end

end
